"""motivo da revogacao do refresh token

Revision ID: d33f7c40f037
Revises: 921122f3d251
Create Date: 2026-08-31 19:19:04.983565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d33f7c40f037"
down_revision: str | Sequence[str] | None = "921122f3d251"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "revoked_reason",
            sa.Enum(
                "ROTACAO",
                "LOGOUT",
                "SEGURANCA",
                name="motivorevogacao",
                native_enum=False,
                length=12,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "revoked_reason")
    # ### end Alembic commands ###
