"""valor de mercado no catalogo, para o prior de Black-Litterman

Revision ID: f8813ba99761
Revises: 87b83d0cbb9f
Create Date: 2026-09-07 15:29:30.074240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8813ba99761"
down_revision: str | Sequence[str] | None = "87b83d0cbb9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets", sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "market_cap")
    # ### end Alembic commands ###
