"""cria tabela transactions

Revision ID: 0f89fa7b4480
Revises: 7fe2c4c3d690
Create Date: 2026-08-31 14:40:09.284257

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f89fa7b4480"
down_revision: str | Sequence[str] | None = "7fe2c4c3d690"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "side",
            sa.Enum("COMPRA", "VENDA", name="transactionside", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("traded_at", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fees >= 0", name=op.f("ck_transactions_taxas_nao_negativas")),
        sa.CheckConstraint("price > 0", name=op.f("ck_transactions_preco_positivo")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_transactions_quantidade_positiva")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_transactions_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(op.f("ix_transactions_traded_at"), "transactions", ["traded_at"], unique=False)
    op.create_index(
        "ix_transactions_user_asset_data",
        "transactions",
        ["user_id", "asset_id", "traded_at"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index("ix_transactions_user_asset_data", table_name="transactions")
    op.drop_index(op.f("ix_transactions_traded_at"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
