"""area de trade: fixado no trade, e sai a meta da carteira

Revision ID: 87b83d0cbb9f
Revises: b95033142c72
Create Date: 2026-09-02 17:14:57.808238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87b83d0cbb9f"
down_revision: str | Sequence[str] | None = "b95033142c72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset_targets",
        sa.Column("fixado_no_trade", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.drop_column("portfolios", "meta_valor")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column(
            "meta_valor", sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("asset_targets", "fixado_no_trade")
    # ### end Alembic commands ###
