"""cria portfolio_snapshots

Revision ID: 921122f3d251
Revises: ef18acbf7c04
Create Date: 2026-08-31 15:37:29.227460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "921122f3d251"
down_revision: str | Sequence[str] | None = "ef18acbf7c04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshots",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("custo_total", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("valor_mercado", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("resultado_nao_realizado", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("resultado_realizado", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("ativos", sa.Integer(), nullable=False),
        sa.Column("ativos_sem_cotacao", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_portfolio_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "date", name=op.f("pk_portfolio_snapshots")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_snapshots")
    # ### end Alembic commands ###
