"""confirmacao de email no cadastro

Revision ID: 3621b2863c09
Revises: f8813ba99761
Create Date: 2026-09-11 11:06:34.287725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3621b2863c09"
down_revision: str | Sequence[str] | None = "f8813ba99761"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_confirmation_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_confirmation_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_confirmation_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_confirmation_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_email_confirmation_tokens_user_id"),
        "email_confirmation_tokens",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("email_confirmado_em", sa.DateTime(timezone=True), nullable=True)
    )
    # Contas anteriores a esta coluna nascem confirmadas. Elas se cadastraram
    # quando nao havia o que confirmar; deixa-las com a coluna nula trancaria do
    # lado de fora quem ja usa o app -- e, sem SMTP configurado, para sempre.
    op.execute(
        "UPDATE users SET email_confirmado_em = created_at WHERE email_confirmado_em IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_confirmado_em")
    op.drop_index(
        op.f("ix_email_confirmation_tokens_user_id"), table_name="email_confirmation_tokens"
    )
    op.drop_table("email_confirmation_tokens")
    # ### end Alembic commands ###
