"""alvo de preco stop gain e stop loss por ativo

Revision ID: 0be96cdf8842
Revises: 5cbc599d4df2
Create Date: 2026-09-02 12:49:28.168564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0be96cdf8842"
down_revision: str | Sequence[str] | None = "5cbc599d4df2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_targets",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stop_gain_tipo",
            sa.Enum(
                "percentual",
                "preco",
                name="tipoalvo_gain",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("stop_gain_valor", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "stop_loss_tipo",
            sa.Enum(
                "percentual",
                "preco",
                name="tipoalvo_loss",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("stop_loss_valor", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(stop_gain_tipo IS NULL) = (stop_gain_valor IS NULL)",
            name=op.f("ck_asset_targets_stop_gain_tipo_e_valor_juntos"),
        ),
        sa.CheckConstraint(
            "(stop_loss_tipo IS NULL) = (stop_loss_valor IS NULL)",
            name=op.f("ck_asset_targets_stop_loss_tipo_e_valor_juntos"),
        ),
        sa.CheckConstraint(
            "stop_gain_valor IS NULL OR stop_gain_valor > 0",
            name=op.f("ck_asset_targets_stop_gain_valor_positivo"),
        ),
        sa.CheckConstraint(
            "stop_loss_valor IS NULL OR stop_loss_valor > 0",
            name=op.f("ck_asset_targets_stop_loss_valor_positivo"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_targets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_asset_targets_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_asset_targets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "asset_id", name=op.f("pk_asset_targets")),
    )
    op.create_index(op.f("ix_asset_targets_user_id"), "asset_targets", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asset_targets_user_id"), table_name="asset_targets")
    op.drop_table("asset_targets")
    # ### end Alembic commands ###
