"""remove confirmacao de e-mail

Revision ID: 0fe51817224f
Revises: 3621b2863c09
Create Date: 2026-09-13 15:36:02.245696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fe51817224f"
down_revision: str | Sequence[str] | None = "3621b2863c09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    O fluxo de confirmacao saiu do projeto. O motivo nao foi de produto: o
    plano Free do Render bloqueia as portas SMTP (25, 465 e 587) desde
    26/09/2025, entao NENHUM e-mail sai de la -- e a trava que exigia SMTP em
    producao impedia ate o app de subir. Confirmar e-mail sem conseguir enviar
    e-mail e uma porta trancada sem chave: todo cadastro ficava presente e
    inacessivel.

    Perde-se a data de confirmacao das contas existentes. E aceitavel: sem o
    fluxo, esse dado nao responde mais nenhuma pergunta. O downgrade recria o
    schema, nao os dados.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_email_confirmation_tokens_user_id"), table_name="email_confirmation_tokens"
    )
    op.drop_table("email_confirmation_tokens")
    op.drop_column("users", "email_confirmado_em")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_confirmado_em",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "email_confirmation_tokens",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_confirmation_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_confirmation_tokens")),
        sa.UniqueConstraint(
            "token_hash",
            name=op.f("uq_email_confirmation_tokens_token_hash"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_email_confirmation_tokens_user_id"),
        "email_confirmation_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
