"""cria assets e price_history

Revision ID: 7fe2c4c3d690
Revises: 03986b9da687
Create Date: 2026-08-31 14:29:36.773864

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe2c4c3d690"
down_revision: str | Sequence[str] | None = "03986b9da687"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("ticker", sa.String(length=12), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=True),
        sa.Column("setor", sa.String(length=80), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "ACAO",
                "FII",
                "ETF",
                "UNIT",
                "BDR",
                "OUTRO",
                name="assettype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("ticker", name=op.f("uq_assets_ticker")),
    )
    op.create_table(
        "price_history",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_price_history_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("asset_id", "date", name=op.f("pk_price_history")),
    )
    op.create_index("ix_price_history_date", "price_history", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_history_date", table_name="price_history")
    op.drop_table("price_history")
    op.drop_table("assets")
    # ### end Alembic commands ###
